### PR TITLE
New versions with security patches for Astronomer 0.13

### PR DESCRIPTION
**Pull request by sjmiller609**
**Summary of changes**:

Andrii did a lot of security patching. In order to make use of these updates in 0.13, we must publish new images that includes the patches. Now is the time to add into 0.13 in order to have vendored components be included in testing.

This PR is versioning the components based on the underlying software as discussed in cloud infra standup. this PR does not change anything other than version lock nginx-es. I am only including the images from Andrii's security patch PR at this point to minimize the change but still get the security patches in.

**Which images are updated by this PR?**:

- [x] alertmanager
- [x] curator
- [x] elasticsearch
- [x] elasticsearch-exporter
- [x] grafana
- [x] kube-state
- [x] nginx
- [x] pgbouncer
- [x] prisma
- [x] redis
- [x] statsd-exporter
- [x] elasticsearch
- [x] fluentd
- [x] kibana
- [x] kubed
- [x] nginx-es
- [x] pgbouncer-exporter
- [x] prometheus
- [x] node-exporter
- [x] registry
- [x] keda
- [x] keda-metrics-adapter
- [x] blackbox-exporter

**Checklist** (required)

Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.

- [x] version.txt is updated in the changed image(s)

If a security scan fails for an unchanged image...

- [ ]  a fix has been applied OR...
- [ ]  an [issue]() has been created

**Additional notes for your reviewer**:

### CODE REVIEW

**Comment by schnie** [comment]
@sjmiller609 should we bump all the images to the new tags with this PR?

**Comment by vishwas-astro** [comment]
@sjmiller609 I thought we were going to have a "-astro" or some sort of suffix to indicate that all these vendor packages are astronomer published. Are we not doing that?

Also, is this ready to merge now?

**Comment by sjmiller609** [comment]
> @sjmiller609 I thought we were going to have a "-astro" or some sort of suffix to indicate that all these vendor packages are astronomer published. Are we not doing that?

we said this is a good plan, however due to input validation, it's not currently supported.

**Comment by sjmiller609** [comment]
@andriisoldatenko thank you so much!

**Pull request merged**
