### PR TITLE
Vendor Image : dogstatsd

### PR DESCRIPTION
**Pull request by howardyoo**
To support Astro's Airflow metric export to DataDog

Signed-off-by: howardyoo <howardyoo@gmail.com>

## Details

Dogstatsd (https://hub.docker.com/r/datadog/dogstatsd) is a varient of datadog agent (https://www.datadoghq.com/) which listens for statsd/dogstatsd metrics and forwards it to datadog service.

Observability team is currently working in creating feature called 'airflow metrics export to 3rd party vendor) that can forward the statsd metrics coming from airflow (in Astro deployment) to DataDog. The team is currently working with harmony and airflow operator team to create the necessary config and deployment for this feature, in order to install and run dogstatsd as a sidecar container inside the statsd pod, we need to have this vendor imaged and pushed into quay.io.

## Related Issues
https://github.com/astronomer/issues/issues/4946

## Checklist
- [x] version.txt was updated

### CODE REVIEW

**Comment by danielhoherd** [comment]
@howardyoo given that this is for the observability team, and given that ap-vendor is entirely components that are shipped with Astronomer "Software", i wonder if https://github.com/astronomer/astro/tree/main/apps/observability isn't a better place for this.

**Comment by howardyoo** [comment]
> @howardyoo given that this is for the observability team, and given that ap-vendor is entirely components that are shipped with Astronomer "Software", I think that https://github.com/astronomer/astro/tree/main/apps/observability is a better place for this. Or maybe somewhere else. The contents of this repo fall onto the "Software" infra team to maintain, and datadog isn't something that we own.

Hmm.. good point. But in that regards, statsd-exporter should also fall under /apps/observability, as that image is also something that is used to collect metrics. Statsd is also not owned by infra team, as well as other softwares - so I wonder what is different with dogstatsd.

**Comment by howardyoo** [comment]
thank you, @pgvishnuram for looking after the build errors.

**Comment by howardyoo** [comment]
> > @howardyoo given that this is for the observability team, and given that ap-vendor is entirely components that are shipped with Astronomer "Software", I think that https://github.com/astronomer/astro/tree/main/apps/observability is a better place for this. Or maybe somewhere else. The contents of this repo fall onto the "Software" infra team to maintain, and datadog isn't something that we own.
> 
> Hmm.. good point. But in that regards, statsd-exporter should also fall under /apps/observability, as that image is also something that is used to collect metrics. Statsd is also not owned by infra team, as well as other softwares - so I wonder what is different with dogstatsd.

@danielhoherd , did you mean this whole `ap-vendor` should be under the belt of the Astronomer Software team? If that's what you said, it makes sense to me.

**Comment by howardyoo** [comment]
@astronomer/ap-vendor-maintainers , I know there are other vendor images that have not passed the trivy tests - but those are not related to this particular vendor image, and this vendor image needs to be pushed into quay.io by next week. Would this be possible? Please let me know, thank you.

**Comment by pgvishnuram** [comment]
Not an issue @howardyoo you need to only approve the image we need pass - once its merged to master just approve dogstatsd

**Comment by howardyoo** [comment]
> 

Hi @pgvishnuram , I do not have authority to approve and merge this PR. @danielhoherd , could you approve this PR to be merged to main?

**Pull request merged**
