### PR TITLE
bumping fluentd version (#2937)

### PR DESCRIPTION
**Pull request by pgvishnuram**
**Which issue this PR fixes**:

**Summary of changes**:

**Which images are updated by this PR?**:

- [ ] alertmanager
- [ ] blackbox-exporter
- [ ] configmap-reloader
- [ ] curator
- [ ] elasticsearch
- [ ] elasticsearch-exporter
- [X] fluentd
- [ ] grafana
- [ ] keda
- [ ] keda-metrics-apiserver
- [ ] kibana
- [ ] kube-state
- [ ] kubed
- [ ] nats-server
- [ ] nats-streaming
- [ ] nginx
- [ ] nginx-es
- [ ] node-exporter
- [ ] pgbouncer
- [ ] pgbouncer-exporter
- [ ] postgres-exporter
- [ ] prisma
- [ ] prometheus
- [ ] redis
- [ ] registry
- [ ] statsd-exporter

**Checklist** (required)

Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.

- [X] version.txt is updated in the changed image(s)

If a security scan fails for an unchanged image...

- [ ]  a fix has been applied OR...
- [X]  an [issue]() has been created

https://github.com/astronomer/issues/issues/2937

If adding a new image:

- [ ] the directory has the same name you intend it to be published as, less a preceding "ap-"
- [ ] the directory includes a file "version.txt", with version matching the underlying software version
- [ ] the directory includes a file "cve-whitelist.yaml", which may be empty
- [ ] the file .github/PULL_REQUEST_TEMPLATE.md is updated to include the image in the checklist
- [ ] execute the script .circleci/generate_circleci_config.py, commit changes to .circleci/config.yml

**Additional notes for your reviewer**:

### CODE REVIEW

**Review by danielhoherd — APPROVED** [review]
Looks good to me. Since we are deviating from just importing the upstream package versions we should probably update the instructions with a simple way to make sure these versions are the latest compatible set.

**Review by vishwas-astro — APPROVED** [review]

**Comment by vishwas-astro** [comment]
> Looks good to me. Since we are deviating from just importing the upstream package versions we should probably update the instructions with a simple way to make sure these versions are the latest compatible set.

@danielhoherd - I thought we are just pulling in 1.12.4 of the upstream fluentd package and some of the other dependencies in the gemfile.

If instructions are needed, where do we update them.

**Comment by danielhoherd** [comment]
@vishwas-astro There are [instructions in the Gemfile itself](https://github.com/astronomer/ap-vendor/blob/main/fluentd/include/Gemfile#L1-L2) about how the file used to be updated. In more recent updates we have deviated from that straight copy/paste to a more nuanced version bump. I looked around for a way to auto-update the Gemfile dependencies to the most recent compatible versions but I can't find anything in Ruby that will do that, which is pretty surprising and also disappointing.

**Comment by vishwas-astro** [comment]
ok @danielhoherd. Thanks for the explanation.

Please suggest a way forward. Thanks!

**Comment by danielhoherd** [comment]
What I'd really like is a tool to auto-resolve the most recent compatible package versions. Something like [pip-compile](https://github.com/jazzband/pip-tools) but for Gemfile. Otherwise we'll have to only update the instructions to say something like "Manually resolve the latest package versions"

**Comment by danielhoherd** [comment]
I opened a discussion on a possible new way to do this where we can dynamically update our versions while still pinning them and keeping track of them. I think it's better than what we have right now. https://astronomer.slack.com/archives/C02NZELT2/p1625616354407900

**Comment by pgvishnuram** [comment]
upstream kubernetes still uses fluent-plugin-kubernetes_metadata_filter 2.6.0 version, we have moved to 2.7.0 in our gem file to address reported CVE.

**Pull request merged**
