### PR TITLE
update ap-nginx image

### PR DESCRIPTION
**Pull request by pgvishnuram**
## Which issue this PR fixes

Currently astronomer platform does not support k8s version >= 1.22, due to ingress controller version compatibility. 
This new image tag fixes that constraint and allows astronomer to run k8s 1.22 without any issues.

Related to https://github.com/astronomer/issues/issues/3934

## Summary of changes

updated ingress controller image from 0.50.0 -> 1.0.2.

## Images are updated by this PR

- [ ] alertmanager
- [ ] awsesproxy
- [ ] blackbox-exporter
- [ ] configmap-reloader
- [ ] curator
- [ ] dind-golang
- [ ] elasticsearch
- [ ] elasticsearch-exporter
- [ ] fluentd
- [ ] git-daemon
- [ ] git-sync
- [ ] grafana
- [ ] keda
- [ ] keda-metrics-apiserver
- [ ] kibana
- [ ] kube-state
- [ ] kubed
- [ ] nats-server
- [ ] nats-streaming
- [ ] nats-exporter
- [x] nginx
- [ ] nginx-es
- [ ] node-exporter
- [ ] openresty
- [ ] pgbouncer
- [ ] pgbouncer-exporter
- [ ] postgresql
- [ ] postgres-exporter
- [ ] prometheus
- [ ] redis
- [ ] registry
- [ ] statsd-exporter

## Checklist

Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.

- [x] version.txt is updated in the changed image(s)

If a security scan fails for an unchanged image...

- [ ] a fix has been applied OR...
- [x] an [issue]() has been created

https://github.com/astronomer/issues/issues/3889
If adding a new image:

- [ ] the directory has the same name you intend it to be published as, less a preceding "ap-"
- [ ] the directory includes a file "version.txt", with version matching the underlying software version
- [ ] the file .github/PULL_REQUEST_TEMPLATE.md is updated to include the image in the checklist
- [ ] execute the script .circleci/generate_circleci_config.py, commit changes to .circleci/config.yml

### CODE REVIEW

**Comment by pgvishnuram** [comment]
@vishwas-astro

**Comment by danielhoherd** [comment]
@pgvishnuram https://github.com/astronomer/issues/issues/3934 says we should go straight to 1.1.x to avoid breaking changes. is there a reason you kept this back to 1.0.x?

**Comment by pgvishnuram** [comment]
I have validated with this version - so added this image  in ap-vendor.

**Comment by danielhoherd** [comment]
@pgvishnuram can you try going to 1.1.x? it would be great to make as much forward progress here as possible, and IIRC going from 1.0.x to 1.1.x was problematic.

**Comment by pgvishnuram** [comment]
@danielhoherd - can you approve now

**Review by danielhoherd — APPROVED** [review]

**Pull request merged**
