### PR TITLE
Ensure that the anon volume for postgres image has the right owner

### PR DESCRIPTION
**Pull request by ashb**
Without this `chown` the `/bitnamin/postgresql` mount point is owned by
root, and Docker uses the owner of that folder to what permissions to
give anon volumes it creates

Without this fix a simple `docker run` of the image fails with this

```
postgresql 14:16:12.66
postgresql 14:16:12.66 Welcome to the Bitnami postgresql container
postgresql 14:16:12.66 Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 14:16:12.67 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 14:16:12.67
postgresql 14:16:12.68 INFO  ==> ** Starting PostgreSQL setup **
postgresql 14:16:12.70 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 14:16:12.70 INFO  ==> Loading custom pre-init scripts...
postgresql 14:16:12.71 INFO  ==> Initializing PostgreSQL database...
mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied
```

## Details

Do not merge this PR until this description is replaced with relevant info about what images are being updated and what changes are being made.

## Related Issues

Do not merge this PR until this text is replaced with links to related issues if one exists, or else this section is deleted.

## Checklist

- [ ] version.txt was updated

### CODE REVIEW

**Review by danielhoherd — APPROVED** [review]
LGTM

**Review by danielhoherd — CHANGES_REQUESTED** [review]
We should add a test for this condition. Here's an example of the kind of test I'm talking about: https://github.com/astronomer/ap-vendor/blob/41b67e827e/curator/test.yaml#L10-L18

**Comment by ashb** [comment]
Yes good idea. What test framework is that YAML file using/driving? I'm not familiar with it

**Comment by danielhoherd** [comment]
@ashb it's something we made. https://github.com/astronomer/ap-vendor/blob/main/bin/test.py#L85-L116

**Comment by ashb** [comment]
I don't know of anything particular that will do this, so this seems fine.

It already fails the test if the command returns non-zero, so I don't actually need to extend anything

**Comment by ashb** [comment]
Test error without my change to the Dockerfile:

```
E           AssertionError: Unexpected exit code 1 for CommandResult(command=b'mkdir /bitnami/postgresql/data', exit_status=1, stdout=None, stderr=b'mkdir: cannot create directory \xe2\x80\x98/bitnami/postgresql/data\xe2\x80\x99: Permission denied\n')
E           assert 1 == 0
E            +  where 1 = CommandResult(command=b'mkdir /bitnami/postgresql/data', exit_status=1, stdout=None, stderr=b'mkdir: cannot create directory "/bitnami/postgresql/data": Permission denied\n').rc
```

**Review by danielhoherd — APPROVED** [review]
Nice little improvements, looks good.

**Review by kaxil — APPROVED** [review]

**Comment by ashb** [comment]
Curious, `make image image_name=postgresql` works, but `bin/docker-operations.py build --project_path=postgresql --image=ap-postgresql` doesn't.

**Comment by ashb** [comment]
Okay, the problem is that CI uses docker-py, which has an issue open for buildkit support since 2019, so it doesn't seem like it'll get that anytime soon 😞

**Comment by ashb** [comment]
Do not merge until #537 is merged.

**Pull request merged**
