### PR TITLE
Additional mapping rule to dogstatsd to control cardinality of local_task_job metric

### PR DESCRIPTION
**Pull request by howardyoo**
This PR adds an entry to ap-vendor's dogstatsd image by applying additional rule to re-map the metric mentioned in #507 

## Details

The changes are defined in #507, but to briefly explain, we're adding the following entry to the dogstatsd.yaml
```yaml
      - match: 'airflow.local_task_job.task_exit.*.*.*.*'
        name: "airflow.local_task_job.task_exit"
        tags:
          dag_id: "$2"
          task_id: "$3"
          exit_code: "$4"
```
This will reduce the multiple metric names shown up in the datadog metrics list
image
into a single metric called `airflow.local_task_job.task_exit` with dag_id, task_id, and exit_code as tags, and removing the job_id part.

## Related Issues

#507 

## Checklist

- [x] version.txt was updated

### CODE REVIEW

**Comment by danielhoherd** [comment]
@howardyoo you should add some reviewers that work with dogstatsd. @pgvishnuram and I do not use dogstatsd, as it is not a gen-1 component, which is the product we work on.

**Comment by howardyoo** [comment]
> @howardyoo you should add some reviewers that work with dogstatsd. @pgvishnuram and I do not use dogstatsd, as it is not a gen-1 component, which is the product we work on.

I don't know of anyone who works with the dogstatsd, except myself - and I did test everything, so it should all be good?

**Review by goutamtadi1 — APPROVED** [review]
LGTM. Were you able to verify the behavior in real time?

**Comment by howardyoo** [comment]
yes, I basically ran a docker image of dogstatsd in my local, applied the
updated yaml, and submitted the same statsd data to verify it.

**Pull request merged**
