### PR TITLE
Fix gemfile

### PR DESCRIPTION
**Pull request by fhoda**
**Which issue this PR fixes**:

Missing packages from Gemfile

**Summary of changes**:

Reverted to older Gemfile with all packages, while keeping any version updates.

**Which images are updated by this PR?**:

- [ ] alertmanager
- [ ] blackbox-exporter
- [ ] configmap-reloader
- [ ] curator
- [ ] elasticsearch
- [ ] elasticsearch-exporter
- [x] fluentd
- [ ] grafana
- [ ] keda
- [ ] keda-metrics-apiserver
- [ ] kibana
- [ ] kube-state
- [ ] kubed
- [ ] nats-server
- [ ] nats-streaming
- [ ] nginx
- [ ] nginx-es
- [ ] node-exporter
- [ ] pgbouncer
- [ ] pgbouncer-exporter
- [ ] postgres-exporter
- [ ] prisma
- [ ] prometheus
- [ ] redis
- [ ] registry
- [ ] statsd-exporter

**Checklist** (required)

Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.

- [x] version.txt is updated in the changed image(s)

If a security scan fails for an unchanged image...

- [ ]  a fix has been applied OR...
- [ ]  an [issue]() has been created

If adding a new image:

- [ ] the directory has the same name you intend it to be published as, less a preceding "ap-"
- [ ] the directory includes a file "version.txt", with version matching the underlying software version
- [ ] the directory includes a file "cve-whitelist.yaml", which may be empty
- [ ] the file .github/PULL_REQUEST_TEMPLATE.md is updated to include the image in the checklist
- [ ] execute the script .circleci/generate_circleci_config.py, commit changes to .circleci/config.yml

**Additional notes for your reviewer**:
This PR is to undo a commit that removed a few packages from the fluentd Gemfile. I tried to make sure I kept any version updates for any packages that were done in that commit. Will definitely need to make sure I didn't miss anything.

### CODE REVIEW

**Review by ianstanton — APPROVED** [review]
LGTM unless there was a reason for removing them. Let's wait for others to review before merging. I know the `fluentd-plugin-s3` gem is required for [this](https://www.astronomer.io/docs/enterprise/v0.23/monitor/logs-to-s3).

**Comment by fhoda** [comment]
I had gem conflicts when using fluentd version `1.12.0` , but those went away when switching `1.11.4`. So I may need to change that here as well.

**Comment by danielhoherd** [comment]
@fhoda what is the reason for reverting to include all the extra packages? AFAIK this is supposed to be updated directly from [upstream](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Gemfile), which did not include all those extra packages.

**Comment by fhoda** [comment]
> @fhoda what is the reason for reverting to include all the extra packages? AFAIK this is supposed to be updated directly from [upstream](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Gemfile), which did not include all those extra packages.

@danielhoherd 

As @ianstanton mentioned some of our capabilities depend on some on those missing packages. s3 being one apparent one. Without the `fluentd-plugin-s3` I don't think this config which we offer in our Astronomer Enterprise charts would work [s3 config](https://github.com/astronomer/astronomer/blob/master/charts/fluentd/values.yaml#L41-L48) .  

Also when I used an image built with the Gemfile before reverting, I got missing gems as dependencies for platform version `0.23.9`. Specifically it was this one `fluent-plugin-rewrite-tag-filter`. I am not sure if some others could have actually been removed so reverted back to what I knew was working.

**Comment by fhoda** [comment]
@danielhoherd , I updated the Gemfile to reflect that changes you requested. Please double check them. Thank you.

**Review by danielhoherd — APPROVED** [review]

**Review by jpweber — APPROVED** [review]

**Pull request merged**
