### PR TITLE
Use docker hub elasticsearch base image 7.13.3

### PR DESCRIPTION
**Pull request by danielhoherd**
Related to https://github.com/astronomer/issues/issues/3191

Switch base image to newer image from docker hub. Old base image had not been updated in 6 months.

Given that this is a different base image we should take extra care to see that it works the same as the previous one. I suspect it will since they were both official.

They are not the same images though:
```
$ diff -W 170 -y 1 2
2021-07-09T16:32:11-0700
danielh $ docker inspect docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1   |	danielh $ docker inspect elasticsearch:7.10.1
[											[
    {											    {
        "Id": "sha256:eb035a6fa72f12b04850ef87504cd31f6e6017c229c098aae972090c39c1  |	        "Id": "sha256:558380375f1a36c20e67c3a0b7bf715c659d75520d0e688b066d5e708918
        "RepoTags": [									        "RepoTags": [
            "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1"		    |	            "elasticsearch:7.10.1"
        ],										        ],
        "RepoDigests": [								        "RepoDigests": [
            "docker.elastic.co/elasticsearch/elasticsearch-oss@sha256:d37649ee302b  |	            "elasticsearch@sha256:7cd88158f6ac75d43b447fdd98c4eb69483fa7bf1be5616a
        ],										        ],
        "Parent": "",									        "Parent": "",
        "Comment": "",									        "Comment": "",
        "Created": "2020-12-05T01:07:55.42916623Z",				    |	        "Created": "2020-12-05T01:07:53.536229274Z",
        "Container": "e2915add0f20898a7b13bd25379e91848cd2833e020c3d1773c572009248  |	        "Container": "41038a9869c8c6b158097fdb5a614cc86fe86278b9ab765f2650c787cc2e
        "ContainerConfig": {								        "ContainerConfig": {
            "Hostname": "e2915add0f20",						    |	            "Hostname": "41038a9869c8",
            "Domainname": "",								            "Domainname": "",
            "User": "",									            "User": "",
            "AttachStdin": false,							            "AttachStdin": false,
            "AttachStdout": false,							            "AttachStdout": false,
            "AttachStderr": false,							            "AttachStderr": false,
            "ExposedPorts": {								            "ExposedPorts": {
                "9200/tcp": {},								                "9200/tcp": {},
                "9300/tcp": {}								                "9300/tcp": {}
            },										            },
            "Tty": false,								            "Tty": false,
            "OpenStdin": false,								            "OpenStdin": false,
            "StdinOnce": false,								            "StdinOnce": false,
            "Env": [									            "Env": [
                "PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:	                "PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:
                "ELASTIC_CONTAINER=true"						                "ELASTIC_CONTAINER=true"
            ],										            ],
            "Cmd": [									            "Cmd": [
                "/bin/sh",								                "/bin/sh",
                "-c",									                "-c",
                "#(nop) ",								                "#(nop) ",
                "CMD [\"eswrapper\"]"							                "CMD [\"eswrapper\"]"
            ],										            ],
            "Image": "sha256:08e2513bc227e07ed7203de5d0f3d62d479ada96d412b4d96e39a  |	            "Image": "sha256:c6c5e8a2beb581f7952fa512a0978935c0f1099d9b103aa6d525b
            "Volumes": null,								            "Volumes": null,
            "WorkingDir": "/usr/share/elasticsearch",					            "WorkingDir": "/usr/share/elasticsearch",
            "Entrypoint": [								            "Entrypoint": [
                "/tini",								                "/tini",
                "--",									                "--",
                "/usr/local/bin/docker-entrypoint.sh"					                "/usr/local/bin/docker-entrypoint.sh"
            ],										            ],
            "OnBuild": null,								            "OnBuild": null,
            "Labels": {									            "Labels": {
                "org.label-schema.build-date": "2020-12-05T01:00:33.671820Z",		                "org.label-schema.build-date": "2020-12-05T01:00:33.671820Z",
                "org.label-schema.license": "Apache-2.0",			    |	                "org.label-schema.license": "Elastic-License",
                "org.label-schema.name": "Elasticsearch",				                "org.label-schema.name": "Elasticsearch",
                "org.label-schema.schema-version": "1.0",				                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://www.elastic.co/products/elasticse	                "org.label-schema.url": "https://www.elastic.co/products/elasticse
                "org.label-schema.usage": "https://www.elastic.co/guide/en/elastic	                "org.label-schema.usage": "https://www.elastic.co/guide/en/elastic
                "org.label-schema.vcs-ref": "1c34507e66d7db1211f66f3513706fdf54873	                "org.label-schema.vcs-ref": "1c34507e66d7db1211f66f3513706fdf54873
                "org.label-schema.vcs-url": "https://github.com/elastic/elasticsea	                "org.label-schema.vcs-url": "https://github.com/elastic/elasticsea
                "org.label-schema.vendor": "Elastic",					                "org.label-schema.vendor": "Elastic",
                "org.label-schema.version": "7.10.1",					                "org.label-schema.version": "7.10.1",
                "org.opencontainers.image.created": "2020-12-05T01:00:33.671820Z",	                "org.opencontainers.image.created": "2020-12-05T01:00:33.671820Z",
                "org.opencontainers.image.documentation": "https://www.elastic.co/	                "org.opencontainers.image.documentation": "https://www.elastic.co/
                "org.opencontainers.image.licenses": "Apache-2.0",		    |	                "org.opencontainers.image.licenses": "Elastic-License",
                "org.opencontainers.image.revision": "1c34507e66d7db1211f66f351370	                "org.opencontainers.image.revision": "1c34507e66d7db1211f66f351370
                "org.opencontainers.image.source": "https://github.com/elastic/ela	                "org.opencontainers.image.source": "https://github.com/elastic/ela
                "org.opencontainers.image.title": "Elasticsearch",			                "org.opencontainers.image.title": "Elasticsearch",
                "org.opencontainers.image.url": "https://www.elastic.co/products/e	                "org.opencontainers.image.url": "https://www.elastic.co/products/e
                "org.opencontainers.image.vendor": "Elastic",				                "org.opencontainers.image.vendor": "Elastic",
                "org.opencontainers.image.version": "7.10.1"				                "org.opencontainers.image.version": "7.10.1"
            }										            }
        },										        },
        "DockerVersion": "19.03.12",							        "DockerVersion": "19.03.12",
        "Author": "",									        "Author": "",
        "Config": {									        "Config": {
            "Hostname": "",								            "Hostname": "",
            "Domainname": "",								            "Domainname": "",
            "User": "",									            "User": "",
            "AttachStdin": false,							            "AttachStdin": false,
            "AttachStdout": false,							            "AttachStdout": false,
            "AttachStderr": false,							            "AttachStderr": false,
            "ExposedPorts": {								            "ExposedPorts": {
                "9200/tcp": {},								                "9200/tcp": {},
                "9300/tcp": {}								                "9300/tcp": {}
            },										            },
            "Tty": false,								            "Tty": false,
            "OpenStdin": false,								            "OpenStdin": false,
            "StdinOnce": false,								            "StdinOnce": false,
            "Env": [									            "Env": [
                "PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:	                "PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:
                "ELASTIC_CONTAINER=true"						                "ELASTIC_CONTAINER=true"
            ],										            ],
            "Cmd": [									            "Cmd": [
                "eswrapper"								                "eswrapper"
            ],										            ],
            "Image": "sha256:08e2513bc227e07ed7203de5d0f3d62d479ada96d412b4d96e39a  |	            "Image": "sha256:c6c5e8a2beb581f7952fa512a0978935c0f1099d9b103aa6d525b
            "Volumes": null,								            "Volumes": null,
            "WorkingDir": "/usr/share/elasticsearch",					            "WorkingDir": "/usr/share/elasticsearch",
            "Entrypoint": [								            "Entrypoint": [
                "/tini",								                "/tini",
                "--",									                "--",
                "/usr/local/bin/docker-entrypoint.sh"					                "/usr/local/bin/docker-entrypoint.sh"
            ],										            ],
            "OnBuild": null,								            "OnBuild": null,
            "Labels": {									            "Labels": {
                "org.label-schema.build-date": "2020-12-05T01:00:33.671820Z",		                "org.label-schema.build-date": "2020-12-05T01:00:33.671820Z",
                "org.label-schema.license": "Apache-2.0",			    |	                "org.label-schema.license": "Elastic-License",
                "org.label-schema.name": "Elasticsearch",				                "org.label-schema.name": "Elasticsearch",
                "org.label-schema.schema-version": "1.0",				                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://www.elastic.co/products/elasticse	                "org.label-schema.url": "https://www.elastic.co/products/elasticse
                "org.label-schema.usage": "https://www.elastic.co/guide/en/elastic	                "org.label-schema.usage": "https://www.elastic.co/guide/en/elastic
                "org.label-schema.vcs-ref": "1c34507e66d7db1211f66f3513706fdf54873	                "org.label-schema.vcs-ref": "1c34507e66d7db1211f66f3513706fdf54873
                "org.label-schema.vcs-url": "https://github.com/elastic/elasticsea	                "org.label-schema.vcs-url": "https://github.com/elastic/elasticsea
                "org.label-schema.vendor": "Elastic",					                "org.label-schema.vendor": "Elastic",
                "org.label-schema.version": "7.10.1",					                "org.label-schema.version": "7.10.1",
                "org.opencontainers.image.created": "2020-12-05T01:00:33.671820Z",	                "org.opencontainers.image.created": "2020-12-05T01:00:33.671820Z",
                "org.opencontainers.image.documentation": "https://www.elastic.co/	                "org.opencontainers.image.documentation": "https://www.elastic.co/
                "org.opencontainers.image.licenses": "Apache-2.0",		    |	                "org.opencontainers.image.licenses": "Elastic-License",
                "org.opencontainers.image.revision": "1c34507e66d7db1211f66f351370	                "org.opencontainers.image.revision": "1c34507e66d7db1211f66f351370
                "org.opencontainers.image.source": "https://github.com/elastic/ela	                "org.opencontainers.image.source": "https://github.com/elastic/ela
                "org.opencontainers.image.title": "Elasticsearch",			                "org.opencontainers.image.title": "Elasticsearch",
                "org.opencontainers.image.url": "https://www.elastic.co/products/e	                "org.opencontainers.image.url": "https://www.elastic.co/products/e
                "org.opencontainers.image.vendor": "Elastic",				                "org.opencontainers.image.vendor": "Elastic",
                "org.opencontainers.image.version": "7.10.1"				                "org.opencontainers.image.version": "7.10.1"
            }										            }
        },										        },
        "Architecture": "amd64",							        "Architecture": "amd64",
        "Os": "linux",									        "Os": "linux",
        "Size": 659143962,							    |	        "Size": 773756675,
        "VirtualSize": 659143962,						    |	        "VirtualSize": 773756675,
        "GraphDriver": {								        "GraphDriver": {
            "Data": {									            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/a97c603bb4d025f4c64b27f00b32  |	                "LowerDir": "/var/lib/docker/overlay2/29a985365c82efa3c2ece1217f8e
                "MergedDir": "/var/lib/docker/overlay2/bb3dd4d2e682b5ed57a08951f68  |	                "MergedDir": "/var/lib/docker/overlay2/ffde02a1f7a960cae8ab2dd64d9
                "UpperDir": "/var/lib/docker/overlay2/bb3dd4d2e682b5ed57a08951f68c  |	                "UpperDir": "/var/lib/docker/overlay2/ffde02a1f7a960cae8ab2dd64d95
                "WorkDir": "/var/lib/docker/overlay2/bb3dd4d2e682b5ed57a08951f68c0  |	                "WorkDir": "/var/lib/docker/overlay2/ffde02a1f7a960cae8ab2dd64d95a
            },										            },
            "Name": "overlay2"								            "Name": "overlay2"
        },										        },
        "RootFS": {									        "RootFS": {
            "Type": "layers",								            "Type": "layers",
            "Layers": [									            "Layers": [
                "sha256:291f6e44771a7b4399b0c6fb40ab4fe0331ddf76eda11080f052b003d9	                "sha256:291f6e44771a7b4399b0c6fb40ab4fe0331ddf76eda11080f052b003d9
                "sha256:15c8dbe5bea12b4734231fe1e70e45df3ba7e87770cd216f573edf6645  |	                "sha256:911490c8ab004e11d1a2148fdafddbd08d5046df14b398044e40453464
                "sha256:b23c183775d612cb5e9cb8385e1429e1b211065450a7861011b9e21c7f  |	                "sha256:8f84abff69b87fd151b7cb86de711cc5d694cc27f03b52fa13f1d6a306
                "sha256:b92b907b0098e086fa44bfc514d9227b08932e399de1e55670cee82b35  |	                "sha256:e2834bada95fe88b11645ce443abbc6450f344b10547e3108bbd372c13
                "sha256:b7ab637c0b05d9cf83fbb06324419c0d101996fd615eb880209aa91be6  |	                "sha256:b456348ecd844f1e2ab37dd9eb899a5c9e65f2e118cbea84294530b108
                "sha256:b9b0aab395382bd90b483f5e123057debfcd6504cd29d24ffe118c43a3  |	                "sha256:3f481e912123167217be535731e2e7a3b732cd1c8c835d21c441a1545e
                "sha256:6cc425efc0537c6f50e03b2916b4f65f309934081c76deb21c549c0653  |	                "sha256:b662ef6f4fc1554cfb00ba613543a44c339c5a5b0be6a19fa1839e4725
                "sha256:ef65fe21497b31eb6e6ce98080e89b1c661e328cfefbd890c6878310b1  |	                "sha256:9117213e7470d2ed125531c3cd0586f4dd985d641c86f499eff5d73e0f
                "sha256:0338e33d891b81f358deac9c37ff4e609d7875a6f6e5607974a6f5cc36  |	                "sha256:d6208dd5807577aed422ae98cd21be3302c0cd96c5e4bcece509f02f98
            ]										            ]
        },										        },
        "Metadata": {									        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"					            "LastTagTime": "0001-01-01T00:00:00Z"
        }										        }
    }											    }
]											]
```

### CODE REVIEW

**Comment by danielhoherd** [comment]
Switching to this new image did not fix the error. `/usr/share/elasticsearch/modules/ingest-geoip/jackson-databind-2.10.4.jar` is not installed by any packages under RH package management.

```
sh-4.4# ls -la /usr/share/elasticsearch/modules/ingest-geoip/jackson-databind-2.10.4.jar
-rw-r--r-- 1 elasticsearch root 1404874 Jul  2 12:07 /usr/share/elasticsearch/modules/ingest-geoip/jackson-databind-2.10.4.jar
sh-4.4# dnf whatprovides /usr/share/elasticsearch/modules/ingest-geoip/jackson-databind-2.10.4.jar
Last metadata expiration check: 0:05:38 ago on Fri Jul  9 23:38:33 2021.
Error: No Matches found
sh-4.4# dnf whatprovides *jackson*
Last metadata expiration check: 0:06:37 ago on Fri Jul  9 23:38:33 2021.
Error: No Matches found
```

**Comment by andriisoldatenko** [comment]
@danielhoherd / @vishwas-astro pls correct me if i'm wrong we want to switch to EE elasticsearch?

**Comment by pgvishnuram** [comment]
@danielhoherd - this PR is no longer needed we have updated elastic images to newer versions

**Comment by andriisoldatenko** [comment]
so let's close this one cc @danielhoherd

**Pull request closed without merging**
