### PR TITLE
update golang version 1.17.8

### PR DESCRIPTION
**Pull request by neel-astro**
Changes: Keeping the golang version up to date in the dind-golang image (updated to 1.17.8)
Reference: https://go.dev/dl/

## Images are updated by this PR

- [ ] alertmanager
- [ ] auth-sidecar
- [ ] awsesproxy
- [ ] blackbox-exporter
- [ ] configmap-reloader
- [ ] curator
- [x] dind-golang
- [ ] elasticsearch
- [ ] elasticsearch-exporter
- [ ] fluentd
- [ ] git-daemon
- [ ] git-sync
- [ ] grafana
- [ ] keda
- [ ] keda-metrics-apiserver
- [ ] kibana
- [ ] kube-state
- [ ] kubed
- [ ] nats-server
- [ ] nats-streaming
- [ ] nats-exporter
- [ ] nginx
- [ ] nginx-es
- [ ] node-exporter
- [ ] openresty
- [ ] pgbouncer
- [ ] pgbouncer-exporter
- [ ] postgresql
- [ ] postgres-exporter
- [ ] prometheus
- [ ] redis
- [ ] registry
- [ ] statsd-exporter

## Checklist

Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.

- [ ] version.txt is updated in the changed image(s)

If a security scan fails for an unchanged image...

- [x] a fix has been applied OR...
- [ ] an [issue]() has been created

If adding a new image:

- [ ] the directory has the same name you intend it to be published as, less a preceding "ap-"
- [ ] the directory includes a file "version.txt", with version matching the underlying software version
- [ ] the file .github/PULL_REQUEST_TEMPLATE.md is updated to include the image in the checklist
- [ ] execute the script .circleci/generate_circleci_config.py, commit changes to .circleci/config.yml

### CODE REVIEW

**Review by danielhoherd — APPROVED** [review]

**Review by danielhoherd — CHANGES_REQUESTED** [review]
version.txt needs to be updated

**Review by danielhoherd — APPROVED** [review]

**Comment by danielhoherd** [comment]
@neel-astro 

> sha256sum: WARNING: 1 of 1 computed checksums did NOT match

**Comment by pgvishnuram** [comment]
> @neel-astro
> 
> > sha256sum: WARNING: 1 of 1 computed checksums did NOT match

its fixed now

**Comment by neel-astro** [comment]
Thanks for fixing it @pgvishnuram

**Pull request merged**
