### PR TITLE
[Software Bot]update postgresql service with version 15.7.0

### PR DESCRIPTION
**Pull request by pgvishnuram**
**** This is an auto generated Pull Request ****
This PR updates  postgresql service with version 15.7.0.

## Related Issues

if relevant, please link to the issue here

## Checklist

- [x] version.txt was updated

### CODE REVIEW

**Comment by Simpcyclassy** [comment]
Why is this PR downgrading the postgres version?

**Comment by pgvishnuram** [comment]
@Simpcyclassy we are mapping multiple versions with single file so we tend keep updating versions with multiple major and minor versions thats why you see the downgrade in here - its still fine and wont impact our existing tag flow

**Comment by Simpcyclassy** [comment]
@pgvishnuram What is the purpose of the mapping?

**Comment by Simpcyclassy** [comment]
OK makes sense now!

**Pull request merged**
