### PR TITLE
Update pgbouncer exporter version

### PR DESCRIPTION
**Pull request by stuart23**
## Details

We see a [bunch of errors](https://astronomer.splunkcloud.com/en-US/app/airflow_astro/search?q=search%20%22could%20not%20get%20stats%3A%20unexpected%20column%3A%20total_server_assignment_count%22%20%7C%20timechart%20count%20by%20clusterId&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=-30d%40d&latest=now&sid=1730745060.1036018&display.page.search.tab=visualizations&display.general.type=visualizations&display.visualizations.charting.chart=line) from the metrics exporter, and no metrics being exported with the latest pgbouncer.

We need these changes for it to work again: https://github.com/jbub/pgbouncer_exporter/pull/32 these are captured in the release https://github.com/jbub/pgbouncer_exporter/releases/tag/v0.18.0 which has the sha 1b1faecd80fdeb0f4d8baa0d423e8b58e4ab9aa5

## Checklist

- [ ] version.txt was updated

### CODE REVIEW

**Review by ianbuss — APPROVED** [review]
LGTM

**Comment by stuart23** [comment]
Need to merge the upstream changes into the [fork](https://github.com/astronomer/pgbouncer_exporter) first

**Comment by stuart23** [comment]
Solves: https://github.com/astronomer/airflow-operator/issues/1954

**Review by danielhoherd — COMMENTED** [review]
Looks good. Thanks for the PR @stuart23!

**Review by danielhoherd — APPROVED** [review]

**Comment by danielhoherd** [comment]
@stuart23 i'm going to close this out because we i was able to switch us back to using the upstream build, which vastly simplifies this dockerfile and removes the need for us to have our own fork of pgbouncer.

**Comment by stuart23** [comment]
Thanks @danielhoherd!

**Pull request closed without merging**
