### PR TITLE
CVE vulnerability fixes for multiple docker services

### PR DESCRIPTION
**Pull request by pgvishnuram**
**Which issue this PR fixes**:

**Summary of changes**:

**Which images are updated by this PR?**:

- [ ] alertmanager
- [ ] blackbox-exporter
- [ ] configmap-reloader
- [ ] curator
- [x] elasticsearch
- [ ] elasticsearch-exporter
- [ ] fluentd
- [x] grafana
- [ ] keda
- [ ] keda-metrics-apiserver
- [x] kibana
- [ ] kube-state
- [ ] kubed
- [x] nats-server
- [ ] nats-streaming
- [ ] nginx
- [ ] nginx-es
- [ ] node-exporter
- [ ] pgbouncer
- [x] pgbouncer-exporter
- [ ] postgres-exporter
- [ ] prisma
- [ ] prometheus
- [ ] redis
- [ ] registry
- [ ] statsd-exporter

**Checklist** (required)

Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.

- [ ] version.txt is updated in the changed image(s)

If a security scan fails for an unchanged image...

- [x]  a fix has been applied OR...
- [ ]  an [issue]() has been created

If adding a new image:

- [ ] the directory has the same name you intend it to be published as, less a preceding "ap-"
- [ ] the directory includes a file "version.txt", with version matching the underlying software version
- [ ] the directory includes a file "cve-whitelist.yaml", which may be empty
- [ ] the file .github/PULL_REQUEST_TEMPLATE.md is updated to include the image in the checklist
- [ ] execute the script .circleci/generate_circleci_config.py, commit changes to .circleci/config.yml

**Additional notes for your reviewer**:

### CODE REVIEW

**Review by ashb — APPROVED** [review]

**Comment by andriisoldatenko** [comment]
@pgvishnuram thanks for PR, few notes:
let's avoid 1 PR for different components, also i've already fixed nats here https://github.com/astronomer/ap-vendor/pull/81.
We just bump nats version instead.

**Comment by andriisoldatenko** [comment]
regarding elasticsearch/kibana:
can you try bump ES to 7.12.0 instead?

**Review by andriisoldatenko — CHANGES_REQUESTED** [review]
added comments.

**Comment by danielhoherd** [comment]
@pgvishnuram please bump the version.txt files in the changed directories

**Comment by andriisoldatenko** [comment]
i'm okey to go with this change. We can bump ES/Kibana in next release.

**Comment by pgvishnuram** [comment]
> regarding elasticsearch/kibana:
> can you try bump ES to 7.12.0 instead?

elasticsearch and kibana OSS versions still behind the mainstream version.

**Pull request closed without merging**
