### PR TITLE
Fix invalid syntax in statsd-exporter configuration

### PR DESCRIPTION
**Pull request by astro-walker**
## Details

Fix some syntax errors introduced by https://github.com/astronomer/ap-vendor/pull/767

The `statsd-exporter` configuration does not support some syntax used in `dogstatsd.yaml`:
https://github.com/astronomer/ap-vendor/blob/179f5e994c195cd7ec8b6357ed1879ecf1884d83/dogstatsd/include/dogstatsd.yaml#L14

https://github.com/prometheus/statsd_exporter/blob/58769c7b4d128e7ceae1cf8d893260ed5b5afa4d/pkg/mapper/mapper.go#L143-L144

https://go.dev/play/p/ED-cXiJX7S1
## Related Issues

This was discovered while testing https://github.com/astronomer/astro/pull/20767. I manually pushed the updated configuration and confirmed that `statsd` runs successfully whereas the prior version causes crashlooping. The affected tag `0.26.1-1` can be deleted from our repositories.

## Checklist

- [x] version.txt was updated

### CODE REVIEW

**Comment by danielhoherd** [comment]
CI incorrectly says that `astrocr.azurecr.io/astronomer/ap-statsd-exporter:0.26.1-2` already exists, probably because of an auth failure:

```
$ docker pull astrocr.azurecr.io/astronomer/ap-statsd-exporter:0.26.1-2
Error response from daemon: Head "https://astrocr.azurecr.io/v2/astronomer/ap-statsd-exporter/manifests/0.26.1-2": unauthorized: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required, visit https://aka.ms/acr/authorization for more information."}]}
```

The repo needs to exist and be publicly accessible.

**Comment by jpweber** [comment]
I delete the tags that already existed that it was complaining about. The tests now pass. Also the public registry is astrocrpublic.azurecr.io so a pull test would be `docker pull astrocr.azurecr.io/astronomer/ap-statsd-exporter:0.26.1-1` would test that it works since the `-2` isn't pushed yet.

**Comment by astro-walker** [comment]
`az acr login -n astrocr && docker pull astrocrpublic.azurecr.io/astronomer/ap-statsd-exporter:0.26.1-1` will also work, I manually pushed the existing tag to the private repo

**Review by danielhoherd — APPROVED** [review]
LGTM

**Pull request merged**
