### PR TITLE
bumping nginx version

### PR DESCRIPTION
**Pull request by rdodev**
**Summary of changes**:

Bumps `nginx` to use version `0.47.0` of ingress controller to address CVEs present in `0.46.0`

**Which images are updated by this PR?**:

- [ ] alertmanager
- [ ] blackbox-exporter
- [ ] configmap-reloader
- [ ] curator
- [ ] elasticsearch
- [ ] elasticsearch-exporter
- [ ] fluentd
- [ ] grafana
- [ ] keda
- [ ] keda-metrics-apiserver
- [ ] kibana
- [ ] kube-state
- [ ] kubed
- [ ] nats-server
- [ ] nats-streaming
- [x] nginx
- [ ] nginx-es
- [ ] node-exporter
- [ ] pgbouncer
- [ ] pgbouncer-exporter
- [ ] postgres-exporter
- [ ] prisma
- [ ] prometheus
- [ ] redis
- [ ] registry
- [ ] statsd-exporter

**Checklist** (required)

Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.

- [x] version.txt is updated in the changed image(s)

If a security scan fails for an unchanged image...

- [ ]  a fix has been applied OR...
- [x]  an [issue]() has been created

### CODE REVIEW

**Review by andriisoldatenko — APPROVED** [review]

**Comment by rdodev** [comment]
A bunch of images seem to be failing Trivy but that's unrelated to this PR. Can someone please merge? @pgvishnuram

**Comment by danielhoherd** [comment]
@rdodev but [nginx is also failing](https://app.circleci.com/pipelines/github/astronomer/ap-vendor/400/workflows/69bc9cc9-d314-4559-858d-348f0cdf1b5e/jobs/27953). Is that a known issue? Should we put in an override?

**Comment by rdodev** [comment]
@danielhoherd yeah basically for what I can see all images are failing trivy, so I think we should override in this case.

**Comment by rdodev** [comment]
@danielhoherd nginx build passing. Added `trivyignore` with pertinent CVE.

**Pull request merged**
