### PR TITLE
Bump statsd-exporter to 0.22.4

### PR DESCRIPTION
**Pull request by ianstanton**
## Which issue this PR fixes

This resolves a request by @howardyoo https://github.com/astronomer/airflow-operator/issues/738

## Summary of changes

Bump statsd-exporter image to 0.22.4

## Images are updated by this PR

- [ ] alertmanager
- [ ] auth-sidecar
- [ ] awsesproxy
- [ ] blackbox-exporter
- [ ] configmap-reloader
- [ ] curator
- [ ] dind-golang
- [ ] elasticsearch
- [ ] elasticsearch-exporter
- [ ] fluentd
- [ ] git-daemon
- [ ] git-sync
- [ ] grafana
- [ ] keda
- [ ] keda-metrics-apiserver
- [ ] kibana
- [ ] kube-state
- [ ] kubed
- [ ] nats-server
- [ ] nats-streaming
- [ ] nats-exporter
- [ ] nginx
- [ ] nginx-es
- [ ] node-exporter
- [ ] openresty
- [ ] pgbouncer
- [ ] pgbouncer-exporter
- [ ] postgresql
- [ ] postgres-exporter
- [ ] prometheus
- [ ] redis
- [ ] registry
- [x] statsd-exporter

## Checklist

Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.

- [x] version.txt is updated in the changed image(s)

If a security scan fails for an unchanged image...

- [ ] a fix has been applied OR...
- [ ] an [issue]() has been created

If adding a new image:

- [ ] the directory has the same name you intend it to be published as, less a preceding "ap-"
- [ ] the directory includes a file "version.txt", with version matching the underlying software version
- [ ] the file .github/PULL_REQUEST_TEMPLATE.md is updated to include the image in the checklist
- [ ] execute the script .circleci/generate_circleci_config.py, commit changes to .circleci/config.yml

### CODE REVIEW

**Comment by ianstanton** [comment]
@pgvishnuram Would you be able to give some hints as to why we're seeing this failure? https://app.circleci.com/pipelines/github/astronomer/ap-vendor/1034/workflows/0a70e0c2-815a-473e-a89a-6487ec3a5e56/jobs/34857 cc @howardyoo

**Comment by pgvishnuram** [comment]
yes adding trivyignore

**Review by pgvishnuram — APPROVED** [review]

**Comment by pgvishnuram** [comment]
@ianstanton ready to merge

**Comment by ianstanton** [comment]
@pgvishnuram thanks! I'm not authorized to merge in this repo. Can you please merge?

**Pull request merged**
