### PR TITLE
bump nats server to 2.2.1 and nats-streaming to 0.21.2

### PR DESCRIPTION
**Pull request by andriisoldatenko**
**Which images are updated by this PR?**:

- [x] nats-server
- [x] nats-streaming

**Checklist** (required)

Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.

- [x] version.txt is updated in the changed image(s)

If a security scan fails for an unchanged image...

- [x]  a fix has been applied OR...
- [x]  an [issue]() has been created

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@danielhoherd i think i saw somewhere ticket for fixing current security issues in ap-vendor repo?

**Comment by andriisoldatenko** [comment]
related PR https://github.com/astronomer/houston-api/pull/673 so we make sure we are using same images everywhere.

**Comment by andriisoldatenko** [comment]
practically works with new versions tested in houston PR  https://github.com/astronomer/houston-api/pull/673

**Comment by vishwas-astro** [comment]
@andriisoldatenko - do we need a corresponding change in astronomer/astronomer charts to include these new versions?

**Comment by andriisoldatenko** [comment]
@vishwas-astro as soon as we release new docker images.

**Review by danielhoherd — APPROVED** [review]

**Pull request merged**
