### PR TITLE
Add UME metrics

### PR DESCRIPTION
**Pull request by BasPH**
## Details

~Got a warning in local Docker Compose setup after adding the `first_task_scheduling_delay` metric. PR currently in draft to figure out the root cause.~

~The warning:~
```
ts=2024-11-14T11:09:26.559Z caller=fsm.go:314 level=warn msg="backtracking required because of match. Performance may be degraded" match=airflow.dagrun.*.first_task_scheduling_delay
```

Used regex matching for `first_task_scheduling_delay` because glob matching requires backtracking and raises above warning in the logs.

## Testing
Tested using local Astro Docker Compose setup:
**docker-compose.override.yml**
```yaml
services:
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - --web.enable-admin-api
      - --web.enable-lifecycle
      # Flags below are defaults, but must be added explicitly, otherwise would be overridden by flags above
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    networks:
      - airflow

  statsd_exporter:
    image: prom/statsd-exporter
    restart: always
    volumes:
      - ./statsd_mapping.yml:/tmp/statsd_mapping.yml
    ports:
      - "9102:9102"
      - "9125:9125/udp"
    command: --statsd.mapping-config=/tmp/statsd_mapping.yml
    networks:
      - airflow
```

**Dockerfile**
```dockerfile
# Airflow 2.10
FROM quay.io/astronomer/astro-runtime:12.3.0
ENV AIRFLOW__METRICS__STATSD_ON=True
ENV AIRFLOW__METRICS__STATSD_HOST=statsd_exporter
ENV AIRFLOW__METRICS__STATSD_PORT=9125
```

Prometheus scrape config:
```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
- job_name: statsd-exporter
  static_configs:
  - targets:
    - statsd_exporter:9102
```

And the **statsd_mapping.yml** from this PR.

Validated by:
1. Letting a DAG with a schedule run at least once
2. Browse to http://localhost:9102/metrics for the statsd_exporter metrics for example:
```
# HELP airflow_dagrun_first_task_scheduling_delay Metric autogenerated by statsd_exporter.
# TYPE airflow_dagrun_first_task_scheduling_delay summary
airflow_dagrun_first_task_scheduling_delay{dag_id="scheduled_dag_test",quantile="0.5"} 1.8853601313039998e+06
airflow_dagrun_first_task_scheduling_delay{dag_id="scheduled_dag_test",quantile="0.9"} 3.4405534623390003e+06
airflow_dagrun_first_task_scheduling_delay{dag_id="scheduled_dag_test",quantile="0.99"} 3.786153179347e+06
airflow_dagrun_first_task_scheduling_delay_sum{dag_id="scheduled_dag_test"} 8.485661479469799e+07
airflow_dagrun_first_task_scheduling_delay_count{dag_id="scheduled_dag_test"} 44

# HELP airflow_task_instance_created Metric autogenerated by statsd_exporter.
# TYPE airflow_task_instance_created counter
airflow_task_instance_created{task_type="BashOperator"} 44
```
3. Validated if I found the same metrics structure in Prometheus

## Related Issues

Do not merge this PR until this text is replaced with links to related issues if one exists, or else this section is deleted.

## Checklist

- [x] version.txt was updated

### CODE REVIEW

**Review by pgvishnuram — APPROVED** [review]

**Review by danielhoherd — APPROVED** [review]
Fine by me. This doesn't affect "Software" though so I think somebody from Astro should review this.

**Review by jpweber — CHANGES_REQUESTED** [review]
There isn't enough information in this PR for me to feel comfortable approving this. No context or motivation for the change. Considering this change would end up going to _all_ dataplanes It is important to see some of this information.

**Comment by astro-walker** [comment]
@jpweber the context here is https://github.com/astronomer/astro/issues/23892 this is a request from Booking: https://astronomer.slack.com/archives/C05HXSJ2Z7B/p1725964484562769

**Comment by jpweber** [comment]
> @jpweber the context here is [astronomer/astro#23892](https://github.com/astronomer/astro/issues/23892)
> 
> This is a request from Booking: https://astronomer.slack.com/archives/C05HXSJ2Z7B/p1725964484562769

excellent. Thank you Walker.

**Review by jpweber — APPROVED** [review]
information has been updated that I feel comfortable approving this now. go forth and emit new metrics. :)

**Pull request merged**
