### PR TITLE
Fix prisma crashloops

### PR DESCRIPTION
**Pull request by andriisoldatenko**
fix https://github.com/astronomer/issues/issues/736

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
practical tests:
```
k logs -f astronomer-prisma-7d5b685b6c-5786k -n astronomer --all-containers=true
Waiting for host: astronomer-postgresql.astronomer.svc.cluster.local 5432
Received response from: astronomer-postgresql.astronomer.svc.cluster.local 5432
...
```

**Comment by andriisoldatenko** [comment]
```
k get pods -n astronomer
NAME                                                READY   STATUS    RESTARTS   AGE
astronomer-cli-install-6546ccf4c8-jncgk             1/1     Running   0          78m
astronomer-commander-59fdbf9ff6-xzwnb               1/1     Running   0          78m
astronomer-houston-744f59c9c6-2thr8                 1/1     Running   0          78m
astronomer-kubed-7bf69d46d-t4gf2                    1/1     Running   0          78m
astronomer-nginx-7dc54d9c7d-b9z7z                   1/1     Running   0          78m
astronomer-nginx-default-backend-7956f565dd-ztjhm   1/1     Running   0          78m
astronomer-orbit-59c7d57c6c-44q9d                   1/1     Running   0          78m
astronomer-postgresql-0                             1/1     Running   0          78m
astronomer-prisma-7dcf9b8b8-h5bhr                   1/1     Running   0          78m
astronomer-registry-0                               1/1     Running   0          78m
```

**Comment by andriisoldatenko** [comment]
cc @sjmiller609 please take a look (fixed security issue via updating sqllite)

**Comment by schnie** [comment]
If we bump these versions, will they automatically ship @sjmiller609?

**Comment by sjmiller609** [comment]
> If we bump these versions, will they automatically ship @sjmiller609?

I expect they will. I expect if they are not updated, then it will fail on the docker push step because there is a check for existing tag before push.

**Comment by andriisoldatenko** [comment]
@schnie @sjmiller609 done.

**Comment by schnie** [comment]
So once this is merged, we will ship ES, Kibana and Prisma images. Should we add the next step of automation in now to carry these version bumps into the `astronomer` chart?

**Comment by andriisoldatenko** [comment]
JFYI practical LGTM in my dev cluster using:
```
  prisma:
    repository: asoldatenko/ap-prisma
    tag: 0.11.0
    pullPolicy: IfNotPresent
```

**Comment by schnie** [comment]
@sjmiller609 @andriisoldatenko bumping the versions on this commit does not feel quite right to me. How are we going to track this stuff? How will we remember to update helm? How do we test this before releasing?

**Comment by sjmiller609** [comment]
> @sjmiller609 @andriisoldatenko bumping the versions on this commit does not feel quite right to me. How are we going to track this stuff? How will we remember to update helm? How do we test this before releasing?

- how will we track? We can look at the git history in this repository to know which version aligns to which code version
- how will we remember to update helm? For now, the developer can PR to the helm chart. Soon we will have automation to do it.
- how do we test it before releasing? For now, we do the same testing we normally do, which is manually checking the edges around our change (for example, Andrii's initial comments in this thread), shipping to stage and making sure everything looks OK, then deploy to prod and monitor key performance and stability metrics. Soon we will have automated tests to run against the Helm chart that test all the core Astronomer functionality on every commit.

**Comment by andriisoldatenko** [comment]
@ashb not add but `update` to fix security issues

**Comment by andriisoldatenko** [comment]
@schnie what's missing here to merge it?

**Pull request merged**
